$(document).ready(function() {
    const modelos = {
        ABARTH: ["500", "500C"],
        "ALFA ROMEO": ["GIULIA", "GIULIETTA", "MITO", "STELVIO", "TONALE"],
        AUDI: [
          "A1",
          "A3",
          "A4",
          "A4 ALLROAD QUATTRO",
          "A5",
          "A6",
          "A6 ALLROAD QUATTRO",
          "A7",
          "A8",
          "Q2",
          "Q3",
          "Q3 SPORTBACK",
          "Q5",
          "Q5 SPORTBACK",
          "Q7",
          "Q8",
          "R8",
          "RS4",
          "RS6",
          "RS7",
          "S1",
          "S5",
          "SQ5",
          "SQ7",
          "TT",
        ],
        BMW: [
          "I3",
          "I8",
          "SERIE 1",
          "SERIE 2",
          "SERIE 2 ACTIVE TOURER",
          "SERIE 2 GRAN TOURER",
          "SERIE 3",
          "SERIE 4",
          "SERIE 5",
          "SERIE 6",
          "SERIE 7",
          "SERIE 8",
          "X1",
          "X2",
          "X3",
          "X4",
          "X5",
          "X6",
          "X7",
          "Z4",
        ],
        CHEVROLET: [
          "AVEO",
          "CAMARO",
          "CAPTIVA",
          "CORVETTE STINGRAY",
          "CRUZE",
          "ORLANDO",
          "SPARK",
          "TRAX",
        ],
        CITROEN: [
          "BERLINGO",
          "C1",
          "C3",
          "C3 AIRCROSS",
          "C3 PICASSO",
          "C4",
          "C4 AIRCROSS",
          "C4 CACTUS",
          "C4 PICASSO",
          "C4 SPACETOURER",
          "C5",
          "C5 AIRCROSS",
          "C5 AIRCROSS HYBRID",
          "C5 X",
          "CELYSEE",
          "DS3",
          "DS4",
          "GRAND C4 PICASSO",
          "GRAND C4 SPACETOURER",
          "SPACETOURER",
        ],
        CUPRA: ["ATECA", "FORMENTOR", "LEON"],
        DACIA: ["DOKKER", "DUSTER", "LODGY", "LOGAN", "SANDERO"],
        DS: [
          "DS 3",
          "DS 3 CROSSBACK",
          "DS 4",
          "DS 4 CROSSBACK",
          "DS 5",
          "DS 7 CROSSBACK",
          "DS 7 CROSSBACK ETENSE",
        ],
        FERRARI: ["458", "488", "812", "CALIFORNIA", "FF", "GTC4", "PORTOFINO"],
        FIAT: [
          "124 SPIDER",
          "500",
          "500C",
          "500L",
          "500X",
          "DOBLO",
          "DOBLO PANORAMA",
          "FREEMONT",
          "FULLBACK",
          "PANDA",
          "PUNTO",
          "QUBO",
          "TIPO",
        ],
        FORD: [
          "BMAX",
          "CMAX",
          "ECOSPORT",
          "EDGE",
          "EXPLORER",
          "FIESTA",
          "FOCUS",
          "FUSION",
          "GALAXY",
          "GRAND C-MAX",
          "GRAND CMAX",
          "GRAND TOURNEO CONNECT",
          "KA",
          "KAPLUS",
          "KUGA",
          "MONDEO",
          "MUSTANG",
          "PUMA",
          "RANGER",
          "SMAX",
          "TOURNEO CONNECT",
          "TOURNEO COURIER",
          "TOURNEO CUSTOM",
        ],
        HONDA: ["CIVIC", "CR-V", "CRV", "HRV", "JAZZ"],
        HYUNDAI: [
          "BAYON",
          "ELANTRA",
          "GRAND SANTA FE",
          "H1 TRAVEL",
          "I10",
          "I20",
          "I20 ACTIVE",
          "I30",
          "I40",
          "IONIQ",
          "IX20",
          "IX35",
          "KONA",
          "SANTA FE",
          "TUCSON",
        ],
        JAGUAR: ["EPACE", "F-PACE", "FPACE", "FTYPE", "XE", "XF"],
        JEEP: [
          "CHEROKEE",
          "COMPASS",
          "GLADIATOR",
          "GRAND CHEROKEE",
          "RENEGADE",
          "WRANGLER",
          "WRANGLER UNLIMITED",
        ],
        KIA: [
          "CARENS",
          "CEE'D",
          "CEED",
          "CEED SPORTSWAGON",
          "CEED TOURER",
          "NIRO",
          "OPTIMA",
          "PICANTO",
          "PRO CEED",
          "PROCEED",
          "RIO",
          "SORENTO",
          "SOUL",
          "SPORTAGE",
          "STONIC",
          "VENGA",
          "XCEED",
        ],
        "LAND-ROVER": [
          "DEFENDER",
          "DISCOVERY",
          "DISCOVERY 4",
          "DISCOVERY SPORT",
          "FREELANDER",
          "RANGE ROVER",
          "RANGE ROVER EVOQUE",
          "RANGE ROVER SPORT",
          "RANGE ROVER VELAR",
        ],
        LEXUS: ["CT", "ES", "GS", "IS", "NX", "RC", "RX", "UX"],
        MAZDA: [
          "CX-3",
          "CX-30",
          "CX-5",
          "CX3",
          "CX30",
          "CX5",
          "CX7",
          "CX9",
          "MAZDA2",
          "MAZDA3",
          "MAZDA5",
          "MAZDA6",
          "MX-5",
          "MX5",
        ],
        "MERCEDES-BENZ": [
          "AMG GT",
          "CITAN",
          "CLA",
          "CLASE A",
          "CLASE B",
          "CLASE C",
          "CLASE CLA",
          "CLASE CLS",
          "CLASE E",
          "CLASE G",
          "CLASE GLA",
          "CLASE GLC",
          "CLASE GLE",
          "CLASE GLE COUPE",
          "CLASE GLK",
          "CLASE GLS",
          "CLASE M",
          "CLASE S",
          "CLASE SLC",
          "CLASE SLK",
          "CLASE T",
          "CLASE V",
          "CLASE X",
          "CLS",
          "GLA",
          "GLB",
          "GLC",
          "GLC COUPE",
          "GLC COUPÉ",
          "GLE",
          "GLE COUPE",
          "MERCEDESAMG GT",
          "VIANO",
          "VITO",
        ],
        MINI: ["CLUBMAN", "COUNTRYMAN", "MINI", "PACEMAN"],
        MITSUBISHI: [
          "ASX",
          "ECLIPSE CROSS",
          "L200",
          "MONTERO",
          "OUTLANDER",
          "SPACE STAR",
        ],
        NISSAN: [
          "370Z",
          "EVALIA",
          "GTR",
          "JUKE",
          "MICRA",
          "NAVARA",
          "NOTE",
          "NV200 EVALIA",
          "PULSAR",
          "QASHQAI",
          "TOWNSTAR",
          "XTRAIL",
        ],
        OPEL: [
          "ADAM",
          "ANTARA",
          "ASTRA",
          "CABRIO",
          "COMBO LIFE",
          "CORSA",
          "CROSSLAND",
          "CROSSLAND X",
          "GRANDLAND",
          "GRANDLAND PHEV",
          "GRANDLAND X",
          "GRANDLAND X PHEV",
          "GTC",
          "INSIGNIA",
          "MERIVA",
          "MOKKA",
          "MOKKA X",
          "VIVARO",
          "ZAFIRA",
          "ZAFIRA LIFE",
          "ZAFIRA TOURER",
        ],
        PEUGEOT: [
          "108",
          "2008",
          "207",
          "208",
          "3008",
          "3008 HYBRID",
          "308",
          "5008",
          "508",
          "508 HYBRID",
          "807",
          "PARTNER",
          "RCZ",
          "RIFTER",
          "TRAVELLER",
        ],
        PORSCHE: [
          "718",
          "911",
          "BOXSTER",
          "CAYENNE",
          "CAYENNE COUPE",
          "CAYMAN",
          "MACAN",
          "PANAMERA",
        ],
        RENAULT: [
          "ARKANA",
          "AUSTRAL",
          "CAPTUR",
          "CLIO",
          "ESPACE",
          "GRAND ESPACE",
          "GRAND SCENIC",
          "KADJAR",
          "KANGOO COMBI",
          "KOLEOS",
          "MEGANE",
          "MÉGANE",
          "SCENIC",
          "TALISMAN",
          "TRAFIC",
          "TWINGO",
        ],
        SEAT: [
          "ALHAMBRA",
          "ALTEA",
          "ARONA",
          "ATECA",
          "EXEO",
          "IBIZA",
          "LEON",
          "MII",
          "TARRACO",
          "TOLEDO",
        ],
        SKODA: [
          "CITIGO",
          "FABIA",
          "KAMIQ",
          "KAROQ",
          "KODIAQ",
          "OCTAVIA",
          "RAPID",
          "SCALA",
          "SCOUT",
          "SPACEBACK",
          "SUPERB",
          "YETI",
        ],
        SMART: ["FORFOUR", "FORTWO"],
        SSANGYONG: ["KORANDO", "REXTON", "RODIUS", "TIVOLI", "XLV"],
        SUBARU: [
          "BRZ",
          "FORESTER",
          "IMPREZA",
          "LEGACY",
          "LEVORG",
          "OUTBACK",
          "WRX STI",
          "XV",
        ],
        SUZUKI: [
          "BALENO",
          "CELERIO",
          "GRAND VITARA",
          "IGNIS",
          "JIMNY",
          "SCROSS",
          "SWIFT",
          "SX4 SCROSS",
          "VITARA",
        ],
        TOYOTA: [
          "AURIS",
          "AVENSIS",
          "AYGO",
          "CHR",
          "COROLLA",
          "HIGHLANDER",
          "HILUX",
          "LAND CRUISER",
          "PRIUS",
          "PRIUSPLUS",
          "PROACE CITY",
          "PROACE VERSO",
          "RAV4",
          "VERSO",
          "YARIS",
          "YARIS CROSS",
        ],
        VOLKSWAGEN: [
          "ARTEON",
          "BEETLE",
          "CADDY",
          "CALIFORNIA",
          "CARAVELLE",
          "CC",
          "GOLF",
          "GOLF SPORTSVAN",
          "JETTA",
          "MULTIVAN",
          "PASSAT",
          "PASSAT CC",
          "POLO",
          "SCIROCCO",
          "SHARAN",
          "TAIGO",
          "TCROSS",
          "TIGUAN",
          "TIGUAN ALLSPACE",
          "TOUAREG",
          "TOURAN",
          "TRANSPORTER",
          "TROC",
          "UP",
        ],
        VOLVO: [
          "S60",
          "S90",
          "V40",
          "V40 CROSS COUNTRY",
          "V60",
          "V60 CROSS COUNTRY",
          "V90",
          "V90 CROSS COUNTRY",
          "XC40",
          "XC60",
          "XC70",
          "XC90",
        ],
    };

    const makeSelect = document.getElementById("make");
    const modelSelect = document.getElementById("model");

    makeSelect.addEventListener("change", (event) => {
        const selectedMake = event.target.value;
        const models = modelos[selectedMake] || [];

        updateModelSelect(modelSelect, models);
    });

    const initialModels = modelos[makeSelect.value] || [];
    updateModelSelect(modelSelect, initialModels);

    function updateModelSelect(selectElement, models) {
        selectElement.innerHTML = "";
    
        for (const model of models) {
            const option = document.createElement("option");
            option.value = model;
            option.textContent = model;
    
            selectElement.appendChild(option);
        }
    }


    $("#car-form").submit(function(event) {
        event.preventDefault();

        const baseUrl = "http://127.0.0.1:5000/car";
        const params = {
            color: $("#color").val(),
            make: $("#make").val(),
            model: $("#model").val(),
            province: $("#province").val(),
            transmission: $("#transmission").val(),
            fuel: $("#fuel").val(),
            body: $("#body").val(),
            seller: $("#seller").val(),
            km: $("#km").val(),
            year: $("#year").val(),
            cv: $("#cv").val(),
            cubic: $("#cubic").val(),
            doors: $("#doors").val(),
        };

        const queryString = $.param(params);
        const url = `${baseUrl}?${queryString}`;

        $.getJSON(url, function(data) {
            if (data.precio) {
                $("#result").html("Precio: " + data.precio);
            } else {
                $("#result").html(data.precio);
            }
        }).fail(function() {
            $("#result").html("Error al obtener el precio");
        });
    });
});
